### ISSUE TITLE
Error with 'rxjs/operators/map'

### ISSUE THREAD

**Issue by octaviomarchi** [creativetimofficial/material-dashboard-angular#29]
I did exactly what is in the Getting Started section.
When I exec `npm start` I get the following error:
```
> md-free-angular-cli@1.4.2 start C:\Dev\creative-tim\material-dashboard-angular2-v1.4.2
> ng serve

module.js:557
    throw err;
    ^

Error: Cannot find module 'rxjs/operators/map'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Dev\creative-tim\material-dashboard-angular2-v1.4.2\node_modules\@angular-devkit\core\src\json\schema\registry.js:15:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! md-free-angular-cli@1.4.2 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the md-free-angular-cli@1.4.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\octavio.parisi\AppData\Roaming\npm-cache\_logs\2018-01-12T15_27_46_161Z-debug.log
```

How do I solve this?

**Comment by octaviomarchi** [comment]
I updated the version of rxjs from 5.4.2 to the current version (5.5.6) and now works :)
